$image = /home/void/downloads/wallpapers/purple-nebula.png

$background = rgba(171216ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(352e34ff)

$inverse_primary = rgba(7d4e7dff)

$inverse_surface = rgba(ebdfe6ff)

$on_background = rgba(ebdfe6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4a204cff)

$on_primary_container = rgba(ffd6faff)

$on_primary_fixed = rgba(320935ff)

$on_primary_fixed_variant = rgba(633664ff)

$on_secondary = rgba(3c2b3bff)

$on_secondary_container = rgba(f5dbf0ff)

$on_secondary_fixed = rgba(261625ff)

$on_secondary_fixed_variant = rgba(534152ff)

$on_surface = rgba(ebdfe6ff)

$on_surface_variant = rgba(d0c3ccff)

$on_tertiary = rgba(4c261dff)

$on_tertiary_container = rgba(ffdad3ff)

$on_tertiary_fixed = rgba(33110aff)

$on_tertiary_fixed_variant = rgba(673b32ff)

$outline = rgba(998d96ff)

$outline_variant = rgba(4d444cff)

$primary = rgba(eeb4eaff)

$primary_container = rgba(633664ff)

$primary_fixed = rgba(ffd6faff)

$primary_fixed_dim = rgba(eeb4eaff)

$scrim = rgba(000000ff)

$secondary = rgba(d8bfd4ff)

$secondary_container = rgba(534152ff)

$secondary_fixed = rgba(f5dbf0ff)

$secondary_fixed_dim = rgba(d8bfd4ff)

$shadow = rgba(000000ff)

$source_color = rgba(b630c2ff)

$surface = rgba(171216ff)

$surface_bright = rgba(3e373cff)

$surface_container = rgba(241e23ff)

$surface_container_high = rgba(2e282dff)

$surface_container_highest = rgba(393338ff)

$surface_container_low = rgba(1f1a1fff)

$surface_container_lowest = rgba(120d11ff)

$surface_dim = rgba(171216ff)

$surface_tint = rgba(eeb4eaff)

$surface_variant = rgba(4d444cff)

$tertiary = rgba(f6b8abff)

$tertiary_container = rgba(673b32ff)

$tertiary_fixed = rgba(ffdad3ff)

$tertiary_fixed_dim = rgba(f6b8abff)

